---
- stat: path="{{ rustc_path }}"
  register: rust_path_result

- name: 'get the rustup installer'
  get_url:
    url: "{{ rustup_installer_url }}"
    dest: "{{ rustup_installer_path }}"
    mode: 0775
  when: rust_path_result.stat.exists == False

- name: 'run the rustup installer'
  command: "{{ rustup_installer_path }} --default-toolchain 1.29.2 --no-modify-path -y"
  become: yes
  become_user: "{{ dev_user }}"
  when: rust_path_result.stat.exists == False

- name: 'install cargo script'
  command: "{{ cargo_path }} install cargo-script"
  become: yes
  become_user: "{{ dev_user }}"
