---
- name: 'install fish from package manager'
  package:
    name: ['fish', 'util-linux-user']
    state: installed

- name: 'get the oh my fish installer'
  get_url:
    url: "{{ omf_installer_url }}"
    dest: "{{ omf_installer_path }}"
    mode: 0777

- name: 'run oh my fish installer'
  command: "{{ omf_installer_path }} --noninteractive"
  args:
    creates: "{{ omf_installed_path }}"
  become: yes
  become_user: "{{ dev_user }}"

- name: 'install themes'
  command: "fish --command='omf install {{ item }}'"
  with_items:
    - bira
    - bobthefish
  become: yes
  become_user: "{{ dev_user }}"

- name: 'remove installer'
  file:
    path: "{{ omf_installer_path }}"
    state: absent
