---
- stat: path="{{ flux_install_path }}"
  register: flux_install_path_result

- name: 'install prerequisites'
  apt:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - libxxf86vm1
    - python-appindicator
    - python-gconf
    - python-glade2
    - python-gtk2
    - python-pexpect
    - python-xdg
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'clone flux repo'
  git:
    repo: "{{ flux_repo_url }}"
    dest: "{{ flux_src_path }}"
  when: flux_install_path_result.stat.exists == False

- name: 'download flux'
  command: 'python download-xflux.py'
  args:
    chdir: "{{ flux_src_path }}"
  when: flux_install_path_result.stat.exists == False

- name: 'install flux'
  command: 'python setup.py install'
  args:
    chdir: "{{ flux_src_path }}"
  when: flux_install_path_result.stat.exists == False
