---
plug_url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
plug_install_path: "/home/{{ dev_user }}/.local/share/nvim/site/autoload"
nvim_config_path: "/home/{{ dev_user }}/.config/nvim"
backup_path: "{{ nvim_config_path }}/backup"
tmp_path: "{{ nvim_config_path }}/tmp"
