---
virtualbox_install_url: "http://download.virtualbox.org/virtualbox/5.2.0/virtualbox-5.2_5.2.0-118431~{{ ansible_distribution }}~{{ ansible_distribution_release }}_amd64.deb"
virtualbox_install_destination: "/tmp/virtualbox-5.2_5.2.0-118431~{{ ansible_distribution }}~{{ ansible_distribution_release }}_amd64.deb"
