---
- name: 'install packages'
  apt:
    name: '{{ item }}'
    state: 'installed'
  with_items:
    - 'cmake'
    - 'curl'
    - 'dos2unix'
    - 'flac'
    - 'git'
    - 'htop'
    - 'mpd'
    - 'mpc'
    - 'ncmpcpp'
    - 'ncurses-dev'
    - 'mpdscribble'
    - 'python-dev'
    - 'silversearcher-ag'
    - 'subversion'
    - 'terminator'
    - 'tree'
    - 'unzip'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
