---
- stat: path="{{ i3_install_path }}"
  register: i3_install_path_result

- name: 'install prerequisites'
  apt:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - autoconf
    - libtool
    - libx11-dev
    - libxcb1-dev
    - libxcb-util-dev
    - pkg-config
    - xutils-dev

- name: 'clone xcb-util-xrm repo'
  git:
    repo: "{{ xcb_util_xrm_repo }}"
    dest: "{{ xcb_util_xrm_path }}"
    recursive: yes
  when: i3_install_path_result.stat.exists == False

- name: 'change submodule reference'
  replace:
    path: "{{ xcb_util_xrm_path }}/.gitmodules"
    regexp: "{{ xcb_util_submodule_reference }}"
    replace: "{{ xcb_util_new_submodule_reference }}"

- name: 'sync submodule update'
  command: 'git submodule sync'
  args:
    chdir: "{{ xcb_util_xrm_path }}"

- name: "update submodules manually (doesn't work as expected in the module)"
  command: 'git submodule update --recursive --init'
  args:
    chdir: "{{ xcb_util_xrm_path }}"

- name: 'run autogen.sh for xcb-util-xrm'
  command: './autogen.sh --prefix=/usr'
  args:
    chdir: "{{ xcb_util_xrm_path }}"
  when: i3_install_path_result.stat.exists == False

- name: 'compile xcb-util-xrm'
  make:
    chdir: "{{ xcb_util_xrm_path }}"
  when: i3_install_path_result.stat.exists == False

- name: 'install xcb-util-xrm'
  make:
    chdir: "{{ xcb_util_xrm_path }}"
    target: install
  when: i3_install_path_result.stat.exists == False
