---
fish_config_path: "/home/{{ dev_user }}/.config/fish"
fish_completions_path: "{{ fish_config_path }}/completions"
omf_installer_url: https://get.oh-my.fish
omf_installer_path: /tmp/omf_installer
omf_installed_path: "/home/{{ dev_user }}/.local/share/omf"
docker_completions_path: "{{ fish_completions_path }}/docker.fish"
docker_completions_url: https://raw.github.com/barnybug/docker-fish-completion/master/docker.fish
