---
- name: 'install apt packages'
  apt:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - 'cmake'
    - 'curl'
    - 'dos2unix'
    - 'flac'
    - 'htop'
    - 'mpc'
    - 'mpd'
    - 'mpdscribble'
    - 'ncmpcpp'
    - 'ncurses-dev'
    - 'python3-pip'
    - 'python-dev'
    - 'python-pygments'
    - 'ranger'
    - 'silversearcher-ag'
    - 'subversion'
    - 'tree'
    - 'unzip'
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: 'install apt packages (gui)'
  apt:
    name: "{{ item }}"
    state: installed
  tags: ['gui']
  with_items:
    - 'keepassx'
    - 'pavucontrol'
    - 'terminator'
    - 'thunar'
    - 'vlc'
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: 'install dnf packages (gui)'
  dnf:
    name: "{{ item }}"
    state: installed
  tags: ['gui']
  with_items:
    - 'keepassx'
    - 'pavucontrol'
    - 'terminator'
    - 'thunar'
    - 'vlc'
  when: ansible_distribution == 'Fedora'

- name: 'install dnf packages (fedora)'
  dnf:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - 'cmake'
    - 'curl'
    - 'dos2unix'
    - 'flac'
    - 'htop'
    - 'libselinux-python'
    - 'mpc'
    - 'mpdscribble'
    - 'ncmpcpp'
    - 'ncurses-devel'
    - 'p7zip'
    - 'python-devel'
    - 'python3-pygments'
    - 'ranger'
    - 'the_silver_searcher'
    - 'subversion'
    - 'tree'
    - 'unzip'
  when: ansible_distribution == 'Fedora'

- name: 'install pip packages (corporate mode)'
  pip:
    name: "{{ item }}"
    extra_args: "--cert /usr/local/share/ca-certificates/corp.crt"
  with_items:
    - 'ansible-lint'
    - 'youtube_dl'
    - 'virtualenv'
    - 'virtualenvwrapper'
  when: corporate_mode

- name: 'install pip packages'
  pip:
    name: "{{ item }}"
  with_items:
    - 'ansible-lint'
    - 'youtube_dl'
    - 'virtualenv'
    - 'virtualenvwrapper'
  when: not corporate_mode

- name: 'install pip3 packages (corporate mode)'
  pip:
    executable: "/usr/bin/pip3"
    name: "{{ item }}"
    extra_args: "--cert /usr/local/share/ca-certificates/corp.crt"
  with_items:
    - 'you-get'
  when: corporate_mode

- name: 'install pip3 packages'
  pip:
    executable: "/usr/bin/pip3"
    name: "{{ item }}"
  with_items:
    - 'you-get'
  when: not corporate_mode
