---
- name: 'install apt packages'
  apt:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - 'cmake'
    - 'curl'
    - 'dos2unix'
    - 'flac'
    #- 'git'
    - 'htop'
    - 'mpc'
    - 'mpd'
    - 'mpdscribble'
    - 'ncmpcpp'
    - 'ncurses-dev'
    - 'python-dev'
    - 'python-pygments'
    - 'silversearcher-ag'
    - 'subversion'
    - 'terminator'
    - 'tree'
    - 'unzip'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# The setup.sh file that runs before provisioning will ensure pip exists.
- name: 'install pip packages'
  pip:
    name: "{{ item }}"
    extra_args: "--cert /usr/local/share/ca-certificates/corp.crt"
  with_items:
    - 'virtualenv'
