---
- name: 'install apt packages'
  apt:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - 'cmake'
    - 'curl'
    - 'direnv'
    - 'dos2unix'
    - 'emacs25'
    - 'flac'
    - 'git'
    - 'htop'
    - 'mpc'
    - 'mpd'
    - 'mpdscribble'
    - 'ncmpcpp'
    - 'ncurses-dev'
    - 'python-dev'
    - 'python-pygments'
    - 'python3-pip'
    - 'python3-venv'
    - 'ranger'
    - 'ShellCheck'
    - 'silversearcher-ag'
    - 'subversion'
    - 'terminator'
    - 'tree'
    - 'unzip'
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: 'install pip on debian'
  apt:
    name: python-pip
    state: present
  when: ansible_distribution in 'Debian'

- name: 'install apt packages (gui)'
  apt:
    name: "{{ item }}"
    state: installed
  tags: ['gui']
  with_items:
    - 'keepassx'
    - 'meld'
    - 'pavucontrol'
    - 'terminator'
    - 'thunar'
    - 'vlc'
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: 'install dnf packages (gui)'
  dnf:
    name: "{{ item }}"
    state: installed
  tags: ['gui']
  with_items:
    - 'gimp'
    - 'i3lock'
    - 'keepassx'
    - 'meld'
    - 'pavucontrol'
    - 'screenshot-tool'
    - 'terminator'
    - 'thunar'
  when: ansible_distribution == 'Fedora'

- name: 'install dnf packages (fedora)'
  dnf:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - 'cmake'
    - 'curl'
    - 'direnv'
    - 'dos2unix'
    - 'emacs'
    - 'flac'
    - 'git'
    - 'htop'
    - 'make'
    - 'mpc'
    - 'mpdscribble'
    - 'ncmpcpp'
    - 'ncurses-devel'
    - 'p7zip'
    - 'python-devel'
    - 'python3-libselinux'
    - 'python3-pygments'
    - 'python3-pip'
    - 'python3-virtualenv'
    - 'ranger'
    - 'the_silver_searcher'
    - 'ShellCheck'
    - 'subversion'
    - 'sysstat'
    - 'terminator'
    - 'tree'
    - 'unzip'
  when: ansible_distribution == 'Fedora'

# For some unknown reason, this package doesn't get installed correctly first time.
- name: 'reinstall python3-pip'
  command: dnf reinstall -y python3-pip
  when: ansible_distribution == 'Fedora'

- name: 'install pip packages (corporate mode)'
  pip:
    name: "{{ item }}"
    extra_args: "--cert /usr/local/share/ca-certificates/corp.crt"
  with_items:
    - 'ansible-lint'
    - 'epc'
    - 'jedi'
    - 'pypsrp'
    - 'youtube_dl'
  when: corporate_mode

- name: 'install pip packages'
  pip:
    name: "{{ item }}"
  with_items:
    - 'ansible-lint'
    - 'epc'
    - 'jedi'
    - 'pypsrp'
    - 'youtube_dl'
  when: not corporate_mode

- name: 'install pip3 packages (corporate mode)'
  pip:
    executable: "/usr/bin/pip3"
    name: "{{ item }}"
    extra_args: "--cert /usr/local/share/ca-certificates/corp.crt"
  with_items:
    - 'virtualfish'
    - 'virtualenv'
    - 'virtualenvwrapper'
    - 'you-get'
  when: corporate_mode

- name: 'install pip3 packages'
  pip:
    executable: "/usr/bin/pip3"
    name: "{{ item }}"
  with_items:
    - 'virtualenv'
    - 'virtualenvwrapper'
    - 'you-get'
