---
- name: 'install apt packages'
  apt:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - 'cmake'
    - 'curl'
    - 'dos2unix'
    - 'flac'
    - 'git'
    - 'htop'
    - 'mpc'
    - 'mpd'
    - 'mpdscribble'
    - 'ncmpcpp'
    - 'ncurses-dev'
    - 'python-dev'
    - 'python-pygments'
    - 'ranger'
    - 'silversearcher-ag'
    - 'subversion'
    - 'terminator'
    - 'tree'
    - 'unzip'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'install apt packages (gui)'
  apt:
    name: "{{ item }}"
    state: installed
  tags: ['gui']
  with_items:
    - 'keepassx'
    - 'pavucontrol'
    - 'thunar'
    - 'vlc'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'install dnf packages (gui)'
  dnf:
    name: "{{ item }}"
    state: installed
  tags: ['gui']
  with_items:
    - 'keepassx'
    - 'pavucontrol'
    - 'thunar'
    - 'vlc'
  when: ansible_distribution == 'Fedora'

- name: 'install dnf packages (fedora)'
  dnf:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - 'cmake'
    - 'curl'
    - 'dos2unix'
    - 'flac'
    - 'git'
    - 'htop'
    - 'libselinux-python'
    - 'mpc'
    - 'mpdscribble'
    - 'ncmpcpp'
    - 'ncurses-devel'
    - 'python-devel'
    - 'python3-pygments'
    - 'ranger'
    - 'the_silver_searcher'
    - 'subversion'
    - 'terminator'
    - 'tree'
    - 'unzip'
  when: ansible_distribution == 'Fedora'

- name: 'install pip packages'
  pip:
    name: "{{ item }}"
  with_items:
    - 'ansible-lint'
    - 'virtualenv'
    - 'virtualenvwrapper'

- name: 'symlink virtualenvwrapper on fedora'
  file:
    src: /usr/bin/virtualenvwrapper.sh
    dest: /usr/local/bin/virtualenvwrapper.sh
    state: link
  when: ansible_distribution == 'Fedora'
