---
ubuntu_docker_installer_url: https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.09.0~ce-0~ubuntu_amd64.deb
docker_installer_destination: /tmp/docker-ce_17.09.0~ce-0~ubuntu_amd64.deb
