---
ubuntu_docker_installer_url: https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.09.0~ce-0~ubuntu_amd64.deb
ubuntu_docker_installer_destination: /tmp/docker-ce_17.09.0~ce-0~ubuntu_amd64.deb
fedora_docker_installer_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/26/x86_64/stable/Packages/docker-ce-17.09.0.ce-1.fc26.x86_64.rpm"
fedora_docker_installer_destination: /tmp/docker-ce_17.09.0.ce-1.fc26.x86_64.rpm
