---
- name: 'create background directory'
  file:
    path: "{{ desktop_background_path }}"
    state: directory
  become_user: "{{ dev_user }}"

- name: 'create nitrogen config directory'
  file:
    path: "{{ nitrogen_config_path }}"
    state: directory
  become_user: "{{ dev_user }}"

- name: 'install nitrogen'
  apt:
    name: nitrogen
    state: 'installed'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'copy desktop backgrounds'
  copy:
    src: "backgrounds/"
    dest: "{{ desktop_background_path }}"
  become_user: "{{ dev_user }}"

- name: 'copy nitrogen config'
  copy:
    src: "nitrogen.cfg"
    dest: "{{ nitrogen_config_path }}/nitrogen.cfg"
  become_user: "{{ dev_user }}"

- name: 'copy bg-saved.cfg for nitrogen'
  template:
    src: "bg-saved.cfg.j2"
    dest: "{{ nitrogen_config_path }}/bg-saved.cfg"
  become_user: "{{ dev_user }}"
