---
- name: 'check if vagrant is installed (debian)'
  command: dpkg-query -W vagrant
  register: vagrant_install_check
  failed_when: vagrant_install_check.rc > 1
  changed_when: vagrant_install_check.rc == 1

- name: 'install vagrant (debian)'
  apt:
    deb: "{{ ubuntu_vagrant_install_url }}"
    state: present
  when: vagrant_install_check.rc == 1
