---
- include: fedora.yml
  when: ansible_distribution == 'Fedora'
- include: debian.yml
  when: ansible_distribution in ['Debian', 'Ubuntu']
- include: ssl.yml
  when: corporate_mode
- include: plugins.yml
