---
- set_fact: dotfiles_repo="{{ dotfiles_repo_https }}"
  when: corporate_mode

- set_fact: dotfiles_repo="{{ dotfiles_repo_ssh }}"
  when: not corporate_mode

- name: 'clone dotfiles'
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_destination }}"
    accept_hostkey: yes
    force: yes
    version: "{{ dotfiles_branch }}"
  become_user: "{{ dev_user }}"
  become: yes

- name: 'bootstrap dotfiles'
  command: "chdir={{ dotfiles_destination }} bash bootstrap.sh"
  become_user: "{{ dev_user }}"
  become: yes

- name: 'create proxy file (corporate mode)'
  template:
    src: proxy.j2
    dest: "/home/{{ dev_user }}/.proxy"
  when: corporate_mode
