---
- name: 'create dotfiles directory'
  file:
    path: "{{ dotfiles_destination }}"
    state: directory
    mode: 0755
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"

- name: 'clone dotfiles'
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_destination }}"
    force: yes
    version: "{{ dotfiles_branch }}"
  become_user: "{{ dev_user }}"
  become: yes

- name: 'bootstrap dotfiles'
  command: "chdir={{ dotfiles_destination }} bash bootstrap.sh"
  become_user: "{{ dev_user }}"
  become: yes

- name: 'bootstrap dockerfiles (this can be a 10+ minute operation)'
  make:
    chdir: "{{ dockerfiles_destination }}"
    target: all
  become_user: "{{ dev_user }}"
  become: yes
