---
- stat: path="{{ git_install_file_path }}"
  register: git_install_path_result

- name: 'set git version for ubuntu'
  set_fact:
    git_apt_version: 2.7.4
  when:
    - ansible_distribution == 'Ubuntu'
    - git_install_path_result.stat.exists == False

- name: 'set git full version for ubuntu'
  set_fact:
    git_apt_full_version: "{{ git_apt_version }}-0ubuntu1.2"
  when:
    - ansible_distribution == 'Ubuntu'
    - git_install_path_result.stat.exists == False

- name: 'install debian prerequisites'
  apt:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - build-essential
    - dpkg-dev
    - fakeroot
    - liberror-perl
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - git_install_path_result.stat.exists == False

- name: 'temporary location for source'
  file:
    state: directory
    path: "{{ git_source_location }}"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - git_install_path_result.stat.exists == False

- name: 'get source using apt-get source'
  shell: "apt-get source git"
  args:
    chdir: "{{ git_source_location }}"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - git_install_path_result.stat.exists == False

- name: 'get build dependencies for git'
  shell: "apt-get build-dep git -y"
  args:
    chdir: "{{ git_source_location }}"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - git_install_path_result.stat.exists == False

# I don't know why this can't just be installed as a normal package.
- name: 'install libcurl4-openssl-dev'
  shell: "apt-get install libcurl4-openssl-dev -y"
  args:
    chdir: "{{ git_source_location }}"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - git_install_path_result.stat.exists == False

- name: 'specify openssl library rather than gnutls'
  replace:
    dest: "{{ git_source_location }}/git-{{ git_apt_version }}/debian/control"
    regexp: "libcurl4-gnutls-dev"
    replace: "libcurl4-openssl-dev"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - git_install_path_result.stat.exists == False

- name: 'disable tests on ubuntu (1 of 42 tests fails on Ubuntu - no resolution on Google)'
  lineinfile:
    dest: "{{ git_source_location }}/git-{{ git_apt_version }}/debian/rules"
    regexp: '^TEST\s*=\s*test'
    state: absent
  when:
    - ansible_distribution == 'Ubuntu'
    - git_install_path_result.stat.exists == False

- name: 'build git (this can take 10+ minutes to run)'
  shell: "dpkg-buildpackage -rfakeroot -b"
  args:
    chdir: "{{ git_source_location }}/git-{{ git_apt_version }}"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - git_install_path_result.stat.exists == False

- name: 'install git man'
  shell: "dpkg -i {{ git_man_package_name }}"
  args:
    chdir: "{{ git_source_location }}"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - git_install_path_result.stat.exists == False

- name: 'install git'
  shell: "dpkg -i {{ git_package_name }}"
  args:
    chdir: "{{ git_source_location }}"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - git_install_path_result.stat.exists == False

- name: 'turn off ssl verification'
  shell: "git config --global http.sslverify false"

- name: 'create file to indicate git is installed'
  file:
    path: "{{ git_install_file_path }}"
    state: touch
    mode: 0644
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
