---
- stat: path="{{ i3blocks_install_path }}"
  register: i3_blocks_install_path_result

- name: 'clone i3blocks repo'
  git:
    repo: "{{ i3blocks_repo }}"
    dest: "{{ i3blocks_src_path }}"
    recursive: yes
  when: i3_blocks_install_path_result.stat.exists == False

- name: 'run autogen'
  command: './autogen.sh'
  args:
    chdir: "{{ i3blocks_src_path }}"
  when: i3_blocks_install_path_result.stat.exists == False

- name: 'run configure'
  command: './configure'
  args:
    chdir: "{{ i3blocks_src_path }}"
  when: i3_blocks_install_path_result.stat.exists == False

- name: 'compile i3blocks'
  make:
    chdir: "{{ i3blocks_src_path }}"
  when: i3_blocks_install_path_result.stat.exists == False

- name: 'install i3blocks'
  make:
    chdir: "{{ i3blocks_src_path }}"
    target: install
  when: i3_blocks_install_path_result.stat.exists == False

- name: 'clone i3blocks contrib repo'
  git:
    repo: "{{ i3blocks_contrib_repo }}"
    dest: "{{ i3blocks_contrib_path }}"
    recursive: yes
  become: yes
  become_user: "{{ dev_user }}"
