---
vundle_repo: https://github.com/VundleVim/Vundle.vim.git
vundle_dir: "/home/{{ dev_user }}/.vim/bundle/Vundle.vim"
plug_url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
plug_install_path: "/home/{{ dev_user }}/.vim/autoload"
dev_path: "/home/{{ dev_user }}/dev"
vim_src_url: "https://github.com/vim/vim/archive/master.zip"
vim_src_archive_path: "{{ dev_path }}/master.zip"
vim_src_path: "{{ dev_path }}/vim-master"
vim_install_path: "/usr/local/bin/vim"
you_complete_me_path: "/home/{{ dev_user }}/.vim/plugged/YouCompleteMe"
