---
- name: 'install zsh from apt'
  apt:
    name: 'zsh'
    state: 'installed'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'install zsh from dnf'
  dnf:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - util-linux-user # installs chsh
    - zsh
  when: ansible_distribution == 'Fedora'

- name: 'download oh-my-zsh installer'
  get_url:
    url: "{{ oh_my_zsh_url }}"
    dest: "/home/{{ dev_user }}/install.sh"
    mode: 0700
  become_user: "{{ dev_user }}"
  become: yes

- name: 'update pam configuration to remove change shell password prompt (fedora)'
  copy:
    src: 'chsh-fedora'
    dest: '/etc/pam.d/chsh'
  when: ansible_distribution == 'Fedora'

# There is a really annoying issue in this installer script when it tries to call chsh
# to set the default shell to zsh. The PAM authentication module complains with a completely
# vague and unhelpful error message: "Critical error - immediate abort". The configuration
# file I had provided got round the issue with some versions of some OSes, but now I'm giving
# up. Just continue on if it produces an error and the user can rectify it manually.
#
# On Ubuntu this prompts for a password, so just run it manually as a post-setup task.
- name: 'install oh-my-zsh'
  shell: "/home/{{ dev_user }}/oh_my_zsh_install.sh"
  args:
    creates: "/home/{{ dev_user }}/.oh-my-zsh"
  become_user: "{{ dev_user }}"
  become: yes
  ignore_errors: yes
  when: ansible_distribution == 'Fedora'

- name: 'remove installer'
  file:
    path: "/home/{{ dev_user }}/oh_my_zsh_install.sh"
    state: absent
  when: ansible_distribution == 'Fedora'

- name: 'install syntax highlighting plugin'
  git:
    repo: "{{ syntax_highlighting_plugin_url }}"
    dest: "{{ syntax_highlighting_plugin_path }}"
    force: yes
  become_user: "{{ dev_user }}"
  become: yes

- name: 'install powerlevel9k theme'
  git:
    repo: "{{ powerlevel9k_theme_url }}"
    dest: "{{ powerlevel9k_theme_path }}"
    force: yes
  become_user: "{{ dev_user }}"
  become: yes
