---
# This role needs to run after rust.
- name: 'clone fzf'
  git:
    repo: "{{ fzf_repo_url }}"
    dest: "{{ fzf_repo_path }}"
    depth: 1
  become: yes
  become_user: "{{ dev_user }}"

- name: 'install fzf'
  command: "{{ fzf_repo_path }}/install --all"
  become: yes
  become_user: "{{ dev_user }}"

- name: 'install packages for building bat'
  dnf:
    name: 'llvm-devel'
    state: 'installed'
  with_items:
    - clang-devel
    - llvm-devel

- name: 'install bat'
  command: "{{ cargo_path }} install bat"
  args:
    creates: "{{ cargo_bin_path }}/bat"
  become: yes
  become_user: "{{ dev_user }}"

- name: 'install devicon-lookup'
  command: "{{ cargo_path }} install devicon-lookup"
  args:
    creates: "{{ cargo_bin_path }}/devicon-lookup"
  become: yes
  become_user: "{{ dev_user }}"
