---
- name: 'install git (debian)'
  apt:
    name: 'git'
    state: installed
  when:
    - ansible_distribution == ['Debian', 'Ubuntu']
    - not corporate_mode

- name: 'install git (fedora)'
  dnf:
    name: 'git'
    state: installed
  when:
    - ansible_distribution == ['Debian', 'Ubuntu']
    - not corporate_mode

- include: custom_ssl_build.yml
  when: corporate_mode
