---
rofi_version: 1.4.2
rofi_archive: "rofi-{{ rofi_version }}.tar.gz"
rofi_url: "https://github.com/DaveDavenport/rofi/releases/download/{{ rofi_version }}/{{ rofi_archive }}"
rofi_tmp_source_path: "/tmp/rofi-{{ rofi_version }}"
rofi_tmp_archive_path: "/tmp/{{ rofi_archive }}"
rofi_install_path: "/usr/local/bin/rofi"
