---
- name: 'debian check if chrome is installed'
  command: dpkg-query -W google-chrome-stable
  register: chrome_install_check
  failed_when: chrome_install_check.rc > 1
  changed_when: chrome_install_check.rc == 1
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'debian install dependencies'
  apt:
    name: '{{ item }}'
    state: 'installed'
  with_items:
    - 'libxss1'
    - 'libappindicator1'
    - 'libindicator7'
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - chrome_install_check.rc == 1

- name: 'debian download chrome stable'
  get_url:
    url: "{{ debian_chrome_install_url }}"
    dest: "{{ chrome_install_destination }}"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - chrome_install_check.rc == 1

- name: 'debian install chrome'
  apt:
    deb: "{{ chrome_install_destination }}"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - chrome_install_check.rc == 1

- name: 'install workstation repositories repo (fedora)'
  dnf:
    name: fedora-workstation-repositories
    state: present
  when: ansible_distribution == 'Fedora'

- name: 'set google-chrome to enabled (fedora)'
  command: "dnf config-manager --set-enabled google-chrome"
  when: ansible_distribution == 'Fedora'

- name: 'enable repo (fedora)'
  copy:
    src: google-chrome.repo
    dest: /etc/yum.repos.d/google-chrome.repo
  when: ansible_distribution == 'Fedora'

- name: 'install chrome (fedora)'
  dnf:
    name: google-chrome-stable
    state: present
  when: ansible_distribution == 'Fedora'
