---
- name: 'check if virtualbox is installed (debian)'
  command: dpkg-query -W virtualbox
  register: virtualbox_install_check
  failed_when: virtualbox_install_check.rc > 1
  changed_when: virtualbox_install_check.rc == 1
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'download virtualbox (debian)'
  get_url:
    url: "{{ virtualbox_install_url }}"
    dest: "{{ virtualbox_install_destination }}"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - virtualbox_install_check.rc == 1

- name: 'install virtualbox (debian)'
  apt:
    deb: "{{ virtualbox_install_destination }}"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - virtualbox_install_check.rc == 1
