---
- name: 'create terraform install path'
  file:
    path: "{{ terraform_install_path }}"
    mode: 0755
    owner: root
    group: root
    state: directory

- name: 'download and unpack terraform'
  unarchive:
    src: "{{ terraform_url }}"
    dest: "{{ terraform_install_path }}"
    remote_src: yes
    creates: "{{ terraform_install_path }}/terraform"

- name: 'link terraform to PATH location'
  file:
    src: "{{ terraform_install_path }}/terraform"
    dest: "/usr/local/bin/terraform"
    state: link
