---
- name: 'install texinfo to make the makeinfo command available'
  apt:
    name: "texinfo"
    state: 'installed'

- name: 'create check src directory'
  file:
    state: directory
    path: "{{ check_tmp_source_path }}"

- name: 'get check'
  get_url:
    url: "{{ check_url }}"
    dest: "{{ check_tmp_archive_path }}"

- name: 'extract source'
  unarchive:
    remote_src: yes
    src: "{{ check_tmp_archive_path }}"
    dest: "{{ check_tmp_source_path }}"

- name: 'run autoreconf'
  command: "autoreconf --install"
  args:
    chdir: "{{ check_tmp_source_path }}/check-{{ check_version }}"

- name: 'configure check'
  command: "./configure"
  args:
    chdir: "{{ check_tmp_source_path }}/check-{{ check_version }}"

- name: 'compile check'
  make:
    chdir: "{{ check_tmp_source_path }}/check-{{ check_version }}"

- name: 'install check'
  make:
    chdir: "{{ check_tmp_source_path }}/check-{{ check_version }}"
    target: install
