---
- name: 'create /etc/ansible directory'
  file:
    path: /etc/ansible
    state: directory
    owner: root
    group: root
    mode: 0755

- name: 'download EC2 dynamic inventory script'
  get_url:
    url: "{{ ec2_inventory_script_url }}"
    dest: /etc/ansible/ec2.py
    owner: root
    group: root
    mode: 0755

- name: 'install boto for use with ec2.py'
  pip:
    name: "boto"
