---
- name: 'install lightdm'
  apt:
    name: lightdm
    state: 'installed'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'install i3'
  apt:
    name: i3
    state: 'installed'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
