---
- stat: path="{{ rofi_install_path }}"
  register: rofi_install_path_result

- include: build-xcb-util-xrm.yml
  when: ansible_distribution == 'Ubuntu' and rofi_install_path_result.stat.exists == False

- name: 'install debian prerequisites'
  apt:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - pkg-config
    - libglib2.0-dev
    - libxcb-xinerama0-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    - libxcb-ewmh-dev
    - libxcb-icccm4-dev
    - libxcb-randr0-dev
    - libxcb-xrm-dev
    - libpango1.0-dev
    - libstartup-notification0-dev
  when: ansible_distribution == 'Debian' and rofi_install_path_result.stat.exists == False

- name: 'install ubuntu prerequisites'
  apt:
    name: "{{ item }}"
    state: 'installed'
  with_items:
    - pkg-config
    - libglib2.0-dev
    - libxcb-xinerama0-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    - libxcb-ewmh-dev
    - libxcb-icccm4-dev
    - libxcb-randr0-dev
    - libxcb-util-dev
    - libpango1.0-dev
    - libstartup-notification0-dev
  when: ansible_distribution == 'Ubuntu' and rofi_install_path_result.stat.exists == False

- name: 'create rofi src directory'
  file:
    state: directory
    path: "{{ rofi_tmp_source_path }}"
  when: rofi_install_path_result.stat.exists == False

- name: 'get rofi'
  get_url:
    url: "{{ rofi_url }}"
    dest: "{{ rofi_tmp_archive_path }}"
  when: rofi_install_path_result.stat.exists == False

- name: 'extract source'
  unarchive:
    remote_src: yes
    src: "{{ rofi_tmp_archive_path }}"
    dest: /tmp
  when: rofi_install_path_result.stat.exists == False

- name: 'configure rofi'
  command: "./configure"
  args:
    chdir: "{{ rofi_tmp_source_path }}"
  when: rofi_install_path_result.stat.exists == False

- name: 'compile rofi'
  make:
    chdir: "{{ rofi_tmp_source_path }}"
  when: rofi_install_path_result.stat.exists == False

- name: 'install rofi'
  make:
    chdir: "{{ rofi_tmp_source_path }}"
    target: install
  when: rofi_install_path_result.stat.exists == False

- name: 'remove tmp files'
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ rofi_tmp_source_path }}"
    - "{{ rofi_tmp_archive_path }}"
