---
- include: directories.yml
  tags: ['vim']
- include: build.yml
  tags: ['vim']
- include: plug.yml
  tags: ['vim']

- name: 'install c++ compiler (fedora)'
  dnf:
    name: 'gcc-c++'
    state: 'installed'
  when: ansible_distribution == 'Fedora'

- name: 'setup ycm core (this compiles YCM so again can take several minutes)'
  command: "{{ you_complete_me_path }}/install.py --clang-completer"
  args:
    creates: "{{ you_complete_me_path }}/third_party/ycmd/ycm_core.so"
  become_user: "{{ dev_user }}"
  become: yes
  tags: ['vim']
