---
- name: 'install neovim via package manager'
  package:
    name: neovim
    state: installed

- include: directories.yml
  tags: ['vim']
- include: plug.yml
  tags: ['vim']

# If you don't install both the Python 2 and 3 version of the neovim package 
# the health check in Neovim will fail. I also had trouble installing them to
# the system wide location, hence the '--user' switch. On the system wide setup
# it kept complaining about the msgpack module being missing, despite the fact
# that it was installed.
- name: 'install python2 neovim package for deoplete (corporate mode)'
  pip:
    name: "neovim"
    extra_args: "--cert /usr/local/share/ca-certificates/corp.crt --user"
  become: yes
  become_user: "{{ dev_user }}"
  when: corporate_mode == False

- name: 'install python2 neovim package for deoplete'
  pip:
    name: "neovim"
    extra_args: "--user"
  become: yes
  become_user: "{{ dev_user }}"

- name: 'install python3 neovim package for deoplete (corporate mode)'
  pip:
    executable: "/usr/bin/pip3"
    name: "neovim"
    extra_args: "--cert /usr/local/share/ca-certificates/corp.crt --user"
  become: yes
  become_user: "{{ dev_user }}"
  when: corporate_mode == False

- name: 'install python3 neovim package for deoplete'
  pip:
    executable: "/usr/bin/pip3"
    name: "neovim"
    extra_args: "--user"
  become: yes
  become_user: "{{ dev_user }}"
