---
- name: 'install fontconfig for fc-cache'
  apt:
    name: fontconfig
    state: 'installed'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'create fonts directory'
  file:
    path: "{{ fonts_directory }}"
    state: directory
    mode: 0755
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"

- name: 'create nerd-fonts directory'
  file:
    path: "{{ nerdfonts_destination }}"
    state: directory
    mode: 0755
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"

- name: "clone nerd fonts (it's a multi GB repository so this will take a long time)"
  git:
    repo: "{{ nerdfonts_repo }}"
    dest: "{{ nerdfonts_destination }}"
    force: yes
  become_user: "{{ dev_user }}"
  become: yes
  tags: ['slow']

- name: 'install nerd fonts - install script will error but it runs fine'
  command: "chdir={{ nerdfonts_destination }} ./install.sh"
  become_user: "{{ dev_user }}"
  become: yes
  ignore_errors: True
  tags: ['slow']

- name: 'refresh font cache'
  shell: "fc-cache -vf {{ fonts_directory }}"
  become_user: "{{ dev_user }}"
  become: yes

- include: freetype.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: freetype-freeworld.yml
  when: ansible_distribution == 'Fedora'
