---
- name: 'install fontconfig for fc-cache'
  apt:
    name: fontconfig
    state: 'installed'

- name: 'create fonts directory'
  file:
    path: "{{ fonts_directory }}"
    state: directory
    mode: 0755
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"

- name: 'create nerd-fonts directory'
  file:
    path: "{{ nerdfonts_destination }}"
    state: directory
    mode: 0755
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"

- name: 'clone nerd fonts'
  git:
    repo: "{{ nerdfonts_repo }}"
    dest: "{{ nerdfonts_destination }}"
    force: yes
  become_user: "{{ dev_user }}"

- name: 'install nerd fonts'
  command: "chdir={{ nerdfonts_destination }} source install.sh"
  become_user: "{{ dev_user }}"

- name: 'refresh font cache'
  shell: "fc-cache -vf {{ fonts_directory }}"
  become_user: "{{ dev_user }}"

- include: infinality.yml
  when: ansible_distribution == 'Debian'
