---
- name: 'install fontconfig for fc-cache'
  apt:
    name: fontconfig
    state: 'installed'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: 'create fonts directory'
  file:
    path: "{{ fonts_directory }}"
    state: directory
    mode: 0755
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"

- name: 'copy fonts to temp directory'
  copy:
    src: "fonts"
    dest: "/tmp"
    owner: "{{ dev_user }}"
    mode: 0664
    group: "{{ dev_user }}"

- name: 'copy fonts to local fonts directory'
  shell: "cp -r /tmp/fonts/** {{ fonts_directory }}"
  become_user: "{{ dev_user }}"
  become: yes

- name: 'refresh font cache'
  shell: "fc-cache -vf {{ fonts_directory }}"
  become_user: "{{ dev_user }}"
  become: yes
